/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#f2f0f0",
        "on-secondary-fixed": "#3f3f3f",
        "background": "#050505",
        "primary": "#EAB308", 
        "secondary-fixed-dim": "#404040",
        "on-primary-fixed-variant": "#EAB308",
        "outline": "#a3a3a3",
        "surface-container-lowest": "#020202",
        "surface-container-high": "#121212",
        "on-error": "#ffefec",
        "on-secondary-container": "#d4d4d4",
        "on-primary-fixed": "#474700",
        "primary-container": "#fce068", 
        "error": "#b02500",
        "secondary": "#a3a3a3",
        "inverse-primary": "#fce068",
        "surface-bright": "#1a1a1a",
        "surface-dim": "#0a0a0a",
        "inverse-on-surface": "#050505",
        "tertiary-dim": "#4f5050",
        "on-error-container": "#ffbab1",
        "secondary-fixed": "#4d4d4d",
        "surface-container-low": "#080808",
        "secondary-dim": "#a3a3a3",
        "primary-fixed": "#EAB308",
        "on-primary": "#ffffff",
        "secondary-container": "#121212",
        "on-tertiary-fixed": "#d4d4d4",
        "tertiary-container": "#121212",
        "on-primary-container": "#5a5a00",
        "surface": "#0a0a0a",
        "on-surface": "#f5f5f5",
        "outline-variant": "#333333",
        "on-tertiary-container": "#e5e5e5",
        "on-tertiary-fixed-variant": "#d4d4d4",
        "on-secondary-fixed-variant": "#d4d4d4",
        "primary-dim": "#c29406",
        "error-container": "#f95630",
        "on-secondary": "#050505",
        "surface-container": "#0e0e0e",
        "inverse-surface": "#f5f5f5",
        "error-dim": "#b92902",
        "tertiary": "#a3a3a3",
        "on-tertiary": "#050505",
        "tertiary-fixed": "#4d4d4d",
        "on-background": "#f5f5f5",
        "surface-tint": "#EAB308",
        "surface-container-highest": "#1a1a1a",
        "on-surface-variant": "#d4d4d4",
        "surface-variant": "#262626",
        "primary-fixed-dim": "#EAB308"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
