/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#888183",
        "on-secondary-fixed": "#ffffff",
        "background": "#4B4E55",
        "primary": "#EAB308",
        "secondary-fixed-dim": "#69686D",
        "on-primary-fixed-variant": "#EAB308",
        "outline": "#a0a0a0",
        "surface-container-lowest": "#3a3c42",
        "surface-container-high": "#69686D",
        "on-error": "#ffefec",
        "on-secondary-container": "#f0f0f0",
        "on-primary-fixed": "#474700",
        "primary-container": "#fce068",
        "error": "#ff6b4a",
        "secondary": "#888183",
        "inverse-primary": "#fce068",
        "surface-bright": "#69686D",
        "surface-dim": "#3a3c42",
        "inverse-on-surface": "#4B4E55",
        "tertiary-dim": "#888183",
        "on-error-container": "#ffdac9",
        "secondary-fixed": "#69686D",
        "surface-container-low": "#4B4E55",
        "secondary-dim": "#888183",
        "primary-fixed": "#EAB308",
        "on-primary": "#ffffff",
        "secondary-container": "#69686D",
        "on-tertiary-fixed": "#ffffff",
        "tertiary-container": "#4B4E55",
        "on-primary-container": "#5a5a00",
        "surface": "#4B4E55",
        "on-surface": "#ffffff",
        "outline-variant": "#888183",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#ffffff",
        "on-secondary-fixed-variant": "#ffffff",
        "primary-dim": "#c29406",
        "error-container": "#930000",
        "on-secondary": "#ffffff",
        "surface-container": "#69686D",
        "inverse-surface": "#f0f0f0",
        "error-dim": "#ffb4a0",
        "tertiary": "#888183",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#69686D",
        "on-background": "#ffffff",
        "surface-tint": "#EAB308",
        "surface-container-highest": "#888183",
        "on-surface-variant": "#e0e0e0",
        "surface-variant": "#888183",
        "primary-fixed-dim": "#EAB308"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
